apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sampleapp
  name: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sampleapp
    spec:
      imagePullSecrets: # calling secrets 
      - name: ashusec # name of secret 
      containers:
      - image: phx.ocir.io/axmbtg8judkl/htmlapp:v1
        name: htmlapp
        resources:
         requests:
          memory: 200M # memory default limit 
          cpu: 200m # cpu core -- 1 vcpu -- 1000 Mili core 
         limits:
          memory: 500M 
          cpu: 300m 
status: {}
